### ISSUE TITLE
Consider lower R version requirement

### ISSUE THREAD

**Issue by henningsway** [mmostly-harmless/ggparty#18]
Currently ggparty requires R >= 3.5.0

Is this really necessary? Would be great to use this also on systems, where R  isn't upgraded that easily or often.

**Comment by martin-borkovec** [comment]
Sorry for the late response.

I don't really know how to determine the minimal required R version... I think the one stated in description was created per default when setting up the package. 

I found this helpful app:
https://twitter.com/andyteucher/status/954856750909349888
According to it the minimal required version would be 3.4 when considering suggests, respectively 3.1 when ignoring those.

However, as you can see on twitter Hadley Wickham has some criticism:

> I’m not 100% sure this is the correct approach. I think the declaration should only concern the version of R used by your package. You can’t control what the deps do. (I think it’s important to know the implied min version but you should then declare it as truth)

Sadly I'm not sure I even fully understand what he means... Is he saying that the version requirements of the dependencies should be completely disregarded?

**Comment by henningsway** [comment]
I also don't know the best way to handle this right now. If I find out, I'll let you know!

**Comment by petermeissner** [comment]
What about trying it out?
I mean a lot changed from 2.x to 3.0 so I would not try out any version before 3.0.
But other than that, since R is very conservative in making changes anyways, it should be reasonable to assume that something runs also on 3.0. 

So give it a try. 

Maybe there is something more elaborate but I thing this should be a reasonable start.

Also there are ways to specify old version of R on Travis so you don't even have to own this R version yourself.

**Comment by martin-borkovec** [comment]
well, as far as i can tell Travis only allows to set the version to "oldrel" which currently corresponds to 3.5.3.

So I tried it out myself on different versions and identified 3.4.0. as the oldest version ggparty can run on. 
This is due to the fact, that it depends on the partykit (which itself only requires >=3.1.0), but wich depends on libcoin (>=1.0-0) which requires >=3.4.0.  

I ran a succesful check without any notes or warnings so if I'm not mistaken the correct requirement for ggparty should be >=3.4.0.
